config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  resources :php_lectures, only: [:index]
  resources :conversations, only:[:index]
  resources :informations, only:[:index]
  resources :video_edits, only:[:index]
  resources :writings, only:[:index]
  resources :aws_lectures,only:[:index, :show]
  resources :lines,only:[:index, :show]
  resources :questions
  resources :questions do
    resources :solutions, only: :create
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_lecture.rb
class AwsLecture < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/line.rb
class Line < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  def self.base_level(page)
    (self.page(page).current_page - 1) * 10
  end
end

app/models/php_lecture.rb
class PhpLecture < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :title, presence: true
  validates :content, presence: true
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video_edit.rb
class VideoEdit < ApplicationRecord
end

app/models/writing.rb
class Writing < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  protect_from_forgery

  def index
    @questions = Question.all
    @questions = Question.all.order(id: "DESC")
  end

  def new
    @question = Question.new
  end

  def create
    Question.create!(question_params)
    redirect_to "/questions"
  end

  def show
    @question = Question.find(params[:id])
    @solution = Solution.new
    @solutions = @question.solutions
  end


  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_color
    controller_name == "lines" ? "bg-success" : "bg-danger"
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    text ||= ''
    render_options = {
      filter_html: false,
      hard_wrap: true
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      autolink: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
      tables: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def bootstrap_movies_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/video_edits_helper.rb
module VideoEditsHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/questions/_form.html.erb
<div class="container-new">
  <%= form_with model: Question.new do |f| %>
    <p>質問投稿</p>
    <p>【タイトル】</p>
    <p><%= f.text_area :title, :size=>"38x1" %></p>
    <p>【内容】</p>
    <p><%= f.text_area :content, :size=>"38x5" %></p>
    <input type="submit" name="commit" value="送信" class="btn btn-primary btn-block btn-lg" data-confirm="新規投稿しますか？" data-disable-with="送信" />
  <% end %>
</div>

app/views/questions/_question.html.erb
<%= link_to(question_path(question)) do %>
  <div class="container-new2">
    <p><%= question.title %></p>
    <p><%= question.content %></p>
    <p><%= l(question.created_at, format: :long) %></p>
  </div>
<% end %>

app/views/questions/create.js.erb
document.getElementById('questions').insertAdjacentHTML('beforebegin', '<%= j(render @question) %>')
document.getElementById('question_title').value = ''
document.getElementById('question_content').value = ''

app/views/questions/index.html.erb
<div class="container-new">
  <%= render 'form' %>
  <hr>
  <%= "質問集" %>
    <div id="questions">
      <%= render @questions %>
    </div>
</div>

app/views/questions/new.html.erb
<div class="container-new">
<%= form_for @question, url: questions_path, html: { method: :post } do |f| %>
  <p>質問投稿</p>
  <p>【タイトル】</p>
  <p><%= f.text_field :title %></p>
  <p>【内容】</p>
  <p><%= f.text_field :content %></p>
  <input type="submit" value="投稿">

<% end %>

</div>

app/views/questions/show.html.erb
<div class="container mt-5" >
  <div class="question">
    <h5>【質問】</h5>
    <p><%= @question.title %></p>
  </div>
  <hr>
  <div class="content">
    <h5 class="mt-4">【詳細】</h5>
    <p><%= markdown(@question.content) %><p>
  </div>
  <hr>
  <div class="solution">
    <% @solutions.each.with_index(1) do |solution,i| %>
      <h5><%= "【回答""#{i}""】"%></h5>
      <p><%= markdown(solution.answer) %><p>
      <hr>
    <% end %>
  </div>
  <div class="post">
    <h3 class="my-3 ">回答投稿</h3>
    <h5>【回答】</h5>
    <%= render 'solutions/form' %>
  </div>
</div>