config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'
  resources :php_lectures, only: [:index]
  resources :conversations, only:[:index]
  resources :informations, only:[:index]
  resources :video_edits, only:[:index]
  resources :writings, only:[:index]
  resources :aws_lectures,only:[:index, :show]
  resources :lines,only:[:index, :show]
  resources :questions
  resources :questions do
    resources :solutions, only: :create
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_lecture.rb
class AwsLecture < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/line.rb
class Line < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  def self.base_level(page)
    (self.page(page).current_page - 1) * 10
  end
end

app/models/php_lecture.rb
class PhpLecture < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :solutions
  validates :title, presence: true
  validates :content, presence: true
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video_edit.rb
class VideoEdit < ApplicationRecord
end

app/models/writing.rb
class Writing < ApplicationRecord
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @articles = Line.all
  end

  def show
    @article = Line.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_color
    controller_name == "lines" ? "bg-success" : "bg-danger"
  end
end

app/helpers/aws_lectures_helper.rb
module AwsLecturesHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    text ||= ''
    render_options = {
      filter_html: false,
      hard_wrap: true
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      autolink: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
      tables: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def bootstrap_movies_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/video_edits_helper.rb
module VideoEditsHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/lines/index.html.erb
<div class="text-center text-success my-4">
  <h2 >LINE@</h2>
</div>
<div class="container">
  <table class="table table-striped">
    <thead class="bg-success text-white">
      <tr>
        <th><div class="w-1">No.</div></th>
        <th><div class="w-2">ジャンル</div></th>
        <th><div class="w-5">内容</div></th>
      </tr>
    </thead>
    <tbody id="myTable">
      <% @articles.each.with_index(1) do |article,i| %>
        <tr>
          <td><div class="text-left"><%= "#{i}" %></div></td>
          <td><div class="text-left"><%= "#{article.genre}" %></div></td>
          <td><div class="text-left"><%= link_to "#{article.title}" , line_path(article.id)%></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lines/show.html.erb
<div class="text-center pt-5 pb-5">
  <h2><%= @article.title %></h2>
</div>
<div class="mx-auto" style="width: 800px;">
  <%= markdown(@article.content) %>
</div>